### PR TITLE
Fix for multiple selectors and skip html/body option

### LINKED ISSUE #2: Option to disable replacing of html and body with wrapper prefix
Hello. I've tried to use this plugin to add prefix to some css frameworks to use them inside specific container. However when it replaces `html` and `body` with wrapper it cause unnecessary styles that applied to container (e.g. min-width, overflows and so on) that breaks container.

```
html {
  background-color: #fff;
  font-size: 16px;
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
  min-width: 300px;
  overflow-x: hidden;
  overflow-y: scroll;
  text-rendering: optimizeLegibility;
}
```

became
```
.mywrapper {
  background-color: #fff;
  font-size: 16px;
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
  min-width: 300px;
  overflow-x: hidden;
  overflow-y: scroll;
  text-rendering: optimizeLegibility;
}
```

Is there any option to avoid this (possibly skip such replacement)?

### LINKED ISSUE #3: Support for multiline selectors
Example 
```
.a,
.b,
.c {color: red}
```

Output:
```
.wrapper .a,
.b,
.c {color: red}
```

So wrapper applied only to `.a` class, but not `.b` and `.c`.

### PR DESCRIPTION
**Pull request by SkeLLLa**
Hello, here's PR for two issues that I've opened:

add option to disable html/body replacement (closes #2)
fix multiple selectors (closes #3)

### CODE REVIEW

**Comment by dbtedman** [comment]
Nicely done, thanks for the contribution.

**Comment by SkeLLLa** [comment]
@dbtedman, no problem. I didn't change changelog, so don't forget to add there some info about that fixes before release/publish.

**Comment by dbtedman** [comment]
Done and done, see 1.1.1 release on npm.

**Comment by SkeLLLa** [comment]
Great!

**Pull request merged**
